// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestTask.Models;

public partial class Users
{
    public int Id { get; set; }

    public string Login { get; set; }

    public string NameLast { get; set; }

    public string NameFirst { get; set; }

    public string NameMiddle { get; set; }

    public string Email { get; set; }
}